backend:
  name: git-gateway
  branch: main # NOTE this relates to your GitHub branch
publish_mode: editorial_workflow
local_backend: true # allows for you to locally mess with your CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
editor:
  preview: false # we're going to hide the preview editor
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Page title (Inga åäö..)", name: "title", widget: "string"}
      - {label: "Titel", name: "displaytitle", widget: "string"}
      - {label: "Publicerat datum", name: "date", widget: "datetime"}
      - {label: "Introbild", name: "thumbnail", widget: "image"}
      - {label: "Introtext", name: "description", widget: "text"}
      - {label: "Innehåll", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "string", default: "../../layouts/RaceLayout.astro"}